[platformio]
default_envs = slavepico-p4

[env:slavepico-p4]
platform = espressif32
board = esp32-p4
framework = arduino
board_build.sdkconfig_defaults = sdkconfig.defaults

upload_speed = 460800
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time

build_flags =
  -O2
  -DCORE_DEBUG_LEVEL=1
  -DSLAVEPICO_ENABLE_DEBUG_LOG=1

lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  robtillaart/M5ROTATE8@^0.4.2
  dfrobot/DFRobot_VisualRotaryEncoder@^1.0.1
