; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:test_minimal]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = waveshare_s3_lcd7
framework = arduino
build_flags = -DMINIMAL_TEST
upload_port = COM20
upload_speed = 460800
monitor_speed = 115200
monitor_port = COM20
build_src_filter = +<main_test.cpp> -<main.cpp> -<drivers/*> -<ui/*>

[env:esp32s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = waveshare_s3_lcd7
framework = arduino
build_src_filter = +<*> -<main_test.cpp>
build_flags = 
	-O2
	-DCORE_DEBUG_LEVEL=0
	-DLV_CONF_INCLUDE_SIMPLE
	-DLV_LVGL_H_INCLUDE_SIMPLE
	-DLV_MEM_CUSTOM=1
	-DLV_MEMCPY_MEMSET_STD=1
	-DLV_ATTRIBUTE_FAST_MEM=IRAM_ATTR
	-I include
	-I src/drivers
	-I src/ui
lib_deps = 
	lvgl/lvgl@^8.4.0
	bblanchon/ArduinoJson@^7.4.0
	robtillaart/M5ROTATE8@^0.4.2
	dfrobot/DFRobot_VisualRotaryEncoder@^1.0.1
upload_port = COM20
upload_speed = 460800
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_extra_dirs =
